version : "3.9"

services :
  backend :
    build : ./backend
    ports :
      - 8000:8000
    # depends_on :
    #   - database
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend :
    build : ./frontend
    ports : 
      - 3000:3000
    depends_on :
      - backend

  # database :
  #   image : mysql
  #   environment :
  #     MYSQL_DATABASE : mydatabase
  #     MYSQL_USER : myuser
  #     MYSQL_PASSWORD : mypassword
  #     MYSQL_ROOT_PASSWORD : myrootpassword
  #   ports :
  #     - 3306:3306

